# Generated by Django 4.2.16 on 2024-10-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[(0, 'Wash and Blow-Dry'), (1, 'Claw Clipping'), (2, 'Coat Trim'), (3, 'Teeth Clean'), (4, 'Flea Treatment and Worming'), (5, 'Paw Ear and Skin Treatment'), (6, 'Therapy Bath')])),
                ('appointmentDay', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
