# Generated by Django 4.2.16 on 2024-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointmentDay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
