# Generated by Django 4.2.16 on 2024-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.IntegerField(choices=[(0, 'Sean'), (1, 'Grace'), (2, 'Roberta')], default=0),
        ),
    ]
