# Generated by Django 4.2.16 on 2024-10-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['appointmentDay']},
        ),
    ]
