# Generated by Django 4.2.16 on 2024-11-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['appointment']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='appointmentDay',
            new_name='appointment',
        ),
    ]
